from __future__ import annotations

import os
import shutil
from urllib.parse import parse_qs, urlencode, urlparse, urlunparse

from campus_jobs.models import CrawlOptions, CrawlResult

from .atsx import ATSXAdapter


class BambuLabAdapter(ATSXAdapter):
    """Bambu Lab's Feishu careers portal.

    This tenant uses portal_type=6 and signed search requests generated by the
    page. Replaying the generic ATSX endpoint directly returns 405, so consume
    the page's own signed /api/v1/search/job/posts response while navigating
    the official pagination URLs.
    """

    name = "bambulab"
    priority = 130

    @classmethod
    def can_handle(cls, url: str) -> bool:
        return (urlparse(url).hostname or "").lower() == "bambulab.jobs.feishu.cn"

    @staticmethod
    def _page_url(url: str, keyword: str, current: int, limit: int) -> str:
        p = urlparse(url)
        q = parse_qs(p.query, keep_blank_values=True)
        if keyword:
            q["keywords"] = [keyword]
        q["current"] = [str(current)]
        q["limit"] = [str(limit)]
        query = urlencode([(k, v) for k, vals in q.items() for v in vals])
        return urlunparse((p.scheme, p.netloc, p.path, p.params, query, p.fragment))

    def crawl(self, url: str, options: CrawlOptions) -> CrawlResult:
        try:
            from playwright.sync_api import sync_playwright
        except ImportError as exc:
            raise RuntimeError("Playwright not installed") from exc

        purl = urlparse(url)
        host = purl.hostname or ""
        root = f"{purl.scheme or 'https'}://{host}"
        jobs = []
        warnings: list[str] = []
        seen: set[str] = set()
        total_count: int | None = None
        actual_page_size: int | None = None

        with sync_playwright() as p:
            launch: dict[str, object] = {"headless": True}
            chrome = next(
                (
                    path
                    for path in [
                        shutil.which("google-chrome"),
                        shutil.which("google-chrome-stable"),
                        shutil.which("chromium"),
                        shutil.which("chromium-browser"),
                    ]
                    if path
                ),
                None,
            )
            if chrome:
                launch["executable_path"] = chrome
            proxy = os.getenv("CAMPUS_JOBS_PROXY", "").strip()
            if proxy:
                launch["proxy"] = {"server": proxy}

            browser = p.chromium.launch(**launch)
            page = browser.new_page(viewport={"width": 1440, "height": 1000})

            for page_index in range(options.max_pages):
                requested_limit = min(max(options.page_size, 1), 100)
                nav_url = self._page_url(url, options.keyword, page_index + 1, requested_limit)
                try:
                    with page.expect_response(
                        lambda r: "/api/v1/search/job/posts" in r.url and r.request.method == "POST",
                        timeout=int(options.timeout * 1000),
                    ) as response_info:
                        page.goto(
                            nav_url,
                            wait_until="domcontentloaded",
                            timeout=int(options.timeout * 1000),
                        )
                    response = response_info.value
                    payload = response.json()
                except Exception as exc:  # noqa: BLE001
                    warnings.append(f"page {page_index + 1}: {type(exc).__name__}: {exc}")
                    break

                data = (payload or {}).get("data") if isinstance(payload, dict) else None
                rows = (data or {}).get("job_post_list") or []
                if total_count is None and isinstance(data, dict):
                    raw_count = data.get("count")
                    if isinstance(raw_count, int):
                        total_count = raw_count
                if not rows:
                    break

                if actual_page_size is None:
                    actual_page_size = len(rows)

                added = 0
                for item in rows:
                    if not isinstance(item, dict):
                        continue
                    job = self._job(item, root, host, options.scope)
                    if job is None or job.id in seen:
                        continue
                    if options.keyword and options.keyword.lower() not in job.full_text.lower():
                        continue
                    seen.add(job.id)
                    jobs.append(job)
                    added += 1
                    if len(jobs) >= options.max_jobs:
                        break

                if len(jobs) >= options.max_jobs:
                    break
                if total_count is not None and len(seen) >= total_count:
                    break
                if added == 0 and page_index > 0:
                    warnings.append(
                        f"pagination stopped at page {page_index + 1}: no new jobs; "
                        f"site may have ignored current={page_index + 1}"
                    )
                    break

            browser.close()

        if total_count is not None and len(jobs) < min(total_count, options.max_jobs):
            warnings.append(
                f"captured {len(jobs)} of site-reported {total_count} jobs "
                f"(page_size={actual_page_size or 0}, max_pages={options.max_pages})"
            )
        return CrawlResult(self.name, url, jobs, warnings)
